import { GoogleGenAI } from "@google/genai";

const getAIClient = () => {
  if (!process.env.API_KEY) {
    throw new Error("API Key not found");
  }
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

export const generateFFmpegExplanation = async (
  currentCommand: string,
  userQuery: string
): Promise<string> => {
  try {
    const ai = getAIClient();
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `
        You are an expert in FFmpeg and video engineering.
        
        Current FFmpeg command generated by the tool:
        \`${currentCommand}\`
        
        The user is asking: "${userQuery}"
        
        Provide a concise, helpful response. 
        If the user wants to achieve a specific effect, provide the modified FFmpeg command or filter chain snippet.
        Keep explanations brief and technical but accessible.
      `,
    });
    return response.text || "I couldn't generate a response.";
  } catch (error) {
    console.error("Gemini API Error:", error);
    return "Error connecting to AI assistant. Please check your API key.";
  }
};